/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as servareNftSol from "./ServareNFT.sol";
export type { servareNftSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { ServareMarketplace } from "./ServareMarketplace";
export type { SupplyChainTracking } from "./SupplyChainTracking";
