/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IServareNFTInterface extends Interface {
  getFunction(
    nameOrSignature: "getProduct" | "ownerOf" | "updateQualityScore"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getProduct",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateQualityScore",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getProduct", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateQualityScore",
    data: BytesLike
  ): Result;
}

export interface IServareNFT extends BaseContract {
  connect(runner?: ContractRunner | null): IServareNFT;
  waitForDeployment(): Promise<this>;

  interface: IServareNFTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getProduct: TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        boolean,
        string,
        boolean,
        bigint,
        bigint
      ] & {
        name: string;
        description: string;
        quantity: bigint;
        location: string;
        expiryDate: bigint;
        productionDate: string;
        category: string;
        imageUri: string;
        price: bigint;
        isListed: boolean;
        producer: string;
        isVerified: boolean;
        carbonFootprint: bigint;
        qualityScore: bigint;
      }
    ],
    "view"
  >;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  updateQualityScore: TypedContractMethod<
    [tokenId: BigNumberish, temperature: BigNumberish, humidity: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getProduct"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        boolean,
        string,
        boolean,
        bigint,
        bigint
      ] & {
        name: string;
        description: string;
        quantity: bigint;
        location: string;
        expiryDate: bigint;
        productionDate: string;
        category: string;
        imageUri: string;
        price: bigint;
        isListed: boolean;
        producer: string;
        isVerified: boolean;
        carbonFootprint: bigint;
        qualityScore: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "updateQualityScore"
  ): TypedContractMethod<
    [tokenId: BigNumberish, temperature: BigNumberish, humidity: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
