/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISupplyChainTracking,
  ISupplyChainTrackingInterface,
} from "../../../contracts/interfaces/ISupplyChainTracking";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "alertType",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "description",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "AlertTriggered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "location",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "status",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "TrackingUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "trackingIndex",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "validator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isValid",
        type: "bool",
      },
    ],
    name: "TrackingValidated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "location",
        type: "string",
      },
      {
        internalType: "string",
        name: "handler",
        type: "string",
      },
      {
        internalType: "string",
        name: "status",
        type: "string",
      },
      {
        internalType: "string[]",
        name: "envKeys",
        type: "string[]",
      },
      {
        internalType: "string[]",
        name: "envValues",
        type: "string[]",
      },
      {
        internalType: "uint256",
        name: "temperature",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "humidity",
        type: "uint256",
      },
    ],
    name: "addTrackingData",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "getTrackingHistory",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "location",
            type: "string",
          },
          {
            internalType: "string",
            name: "handler",
            type: "string",
          },
          {
            internalType: "string",
            name: "status",
            type: "string",
          },
          {
            internalType: "string[]",
            name: "envKeys",
            type: "string[]",
          },
          {
            internalType: "string[]",
            name: "envValues",
            type: "string[]",
          },
          {
            internalType: "uint256",
            name: "temperature",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "humidity",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isValidated",
            type: "bool",
          },
          {
            internalType: "address",
            name: "validator",
            type: "address",
          },
        ],
        internalType: "struct ISupplyChainTracking.TrackingData[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "trackingIndex",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "isValid",
        type: "bool",
      },
      {
        internalType: "string",
        name: "notes",
        type: "string",
      },
    ],
    name: "validateTrackingData",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISupplyChainTracking__factory {
  static readonly abi = _abi;
  static createInterface(): ISupplyChainTrackingInterface {
    return new Interface(_abi) as ISupplyChainTrackingInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISupplyChainTracking {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ISupplyChainTracking;
  }
}
